import { StyleSheet } from "react-native"

export default StyleSheet.create({
    account: {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        marginTop: 5,
        height: "100%",
        backgroundColor: "white"
    },
    title: {
        marginTop: 10,
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
    },
    titleText: {
        fontWeight: "500",
        fontSize: 24,
    },
    block: {
        width: 300,
        height: 350,
        borderRadius: 20,
        borderWidth: 2,
        borderColor: "#000000",
        backgroundColor: "aliceblue",
    },
    form: {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
    },
    text: {
        fontSize: 23
    },
    input: {
        display: "flex",
        flexDirection: "column",
        textAlign: "left",
        marginTop: 10,
        paddingBottom: 20,
        width: 150,
    },
    inputText: {
        marginTop: 5,
        alignSelf: "center",
        width: 200,
        padding: 10,
        fontSize: 26,
        borderWidth: 1.2,
        borderRadius: 15,
        borderColor: "grey",
    },
    confirmButton: {
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        width: 130,
        height: 50,
        borderRadius: 20,
        borderWidth: 1.2,
        borderColor: "blue",
        backgroundColor: "aliceblue"
    },
    confirmButtonText: {
        fontSize: 23,
        fontWeight: "600",
    },
    touchableOpacityPress: {
        shadowColor: "rgb(70, 83, 254)",
        shadowOpacity: 2,
        shadowOffset: {
            height: 5,
            width: 5,
        },
        shadowRadius: 0,
    },
    accountInfo: {
        borderWidth: 1,
        borderColor: "black",
        borderRadius: 20,
        width: 300,
        height: 300,
        backgroundColor: "aliceblue",
        display: "flex",
        flexDirection: "column",
        justifyContent: "space-around",
        alignItems: "center",
    },
    accountInfoRow: {
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        width: 200,
        height: 50,
        borderWidth: 1.2,
        borderColor: "black",
        borderRadius: 23,
    },
    accountInfoRowText: {
        flex: 2.25,
        textAlign: "center",
        fontSize: 20,
        fontWeight: "600",
    },
    accountInfoRowTextPlaceholder: {
        flex: 2.5,
        color: "grey",
        marginLeft: 10,
        textAlign: "left",
        fontSize: 15,
        fontWeight: "600",
    },
})